version: '3.8'

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres_keycloak

  postgres_keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data



volumes:
  postgres_keycloak_data:
