version: '3.8'

services:
  keycloak:
    image: keycloak/keycloak:23.0
    env_file:
      - keycloak.env
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres_keycloak

  postgres_keycloak:
    image: postgres:15
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  postgres_job_database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_job_database:/var/lib/postgresql/data


volumes:
  postgres_keycloak_data:
  postgres_job_database: