server:
  port: 8090
spring:
  application:
    name: job-app
  datasource:
    url: jdbc:postgresql://localhost:5433/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}
  jpa:
    hibernate:
      ddl-auto: create-drop
springdoc:
  swagger-ui:
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

