server:
  port: 8090

spring:
  application:
    name: job-app

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

springdoc:
  swagger-ui:
    oauth:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}

logging:
  level:
    org.example.jobapp: debug

security:
  realm: ${REALM}
  server-url: ${KEYCLOAK_URL}
  client-id: admin-cli
  grant-type: password
  name: ${ADMIN_ID}
  password: ${ADMIN_PASSWORD}
  logout-endpoint: ${LOGOUT_ENDPOINT}
  logout-redirect: ${REDIRECT_URI}
